version: "3.2"

services:
    php-fpm:
        build: 
            context: './docker/php-fpm/'
            args:
                PHP_VERSION: ${PHP_VERSION}
        depends_on:
            - db
        networks:
            - backend
        volumes: 
            - ./html/:/var/www/html/ 
        container_name: "${PHP_NAME}"

    apache:
        build:
            context: './docker/apache/'
            args:
                APACHE_VERSION: ${APACHE_VERSION}
        depends_on:
            - php-fpm
        #      - mariadb
        networks:
            - backend
            - frontend
        ports:
            - "8080:80"
        volumes:
            - ./html/:/var/www/html/
        container_name: "${APACHE_NAME}"
    db:
        image: postgres:latest
        #container_name: "${POSTGRES_NAME}"
        restart: always
        networks:
            - backend
        volumes:
            - ./db_data/:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_HOST: "${POSTGRES_HOST}"
        ports:
            - "54321:5432"

    #  mariadb:
    #    image: mariadb:${MARIADB_VERSION:-latest}
    #    restart: always
    #    ports:
    #      - "3306:3306"
    #    volumes:
    #      - ./mariadb:/var/lib/mysql
    #    networks:
    #      - backend
    #    environment:
    #      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    #      MYSQL_DATABASE: "${DB_NAME}"
    #      MYSQL_USER: "${DB_USERNAME}"
    #      MYSQL_PASSWORD: "${DB_PASSWORD}"
    #    container_name: "${MARIADB_NAME}"
    #
    #  adminer:
    #    image: adminer
    #    ports:
    #      - 8080:8080
    #    networks: - backend
    #    restart: always
    #    container_name: "${ADMINER_NAME}"

networks:
    backend:
    frontend:
